import React from "react";

const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "LAST NAME", uid: "last_name", sortable: true },
  { name: "FIRST NAME", uid: "first_name", sortable: true },
  { name: "DATE OF BIRTH", uid: "dob" },
  { name: "LANGUAGE", uid: "language", sortable: true },
  { name: "SPECIAL NEEDS", uid: "special_need", sortable: true },
  { name: "PARENT/GUARDIAN NAME", uid: "parent_name", sortable: true },
  { name: "RELATIONSHIP", uid: "relationship", sortable: true },
  { name: "PHONE", uid: "phone", sortable: true },
  { name: "EMAIL", uid: "email" },
  { name: "ADDRESS", uid: "address" },
  { name: "CREDIT", uid: "credit", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const participants = [
  {
    id: 1,
    last_name: "Doe",
    first_name: "John",
    dob: "13/05/2016",
    language: "English",
    special_need: "ADHD",
    parent_name: "Jason Doe",
    relationship: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 200,
  },
  {
    id: 2,
    last_name: "Smith",
    first_name: "Jane",
    dob: "23/07/2015",
    language: "French",
    special_need: "None",
    parent_name: "Emily Smith",
    relationship: "mother",
    phone: "647-234-5678",
    email: "emilysmith@gmail.com",
    address: "5000 Yonge St",
    credit: 150,
  },
  {
    id: 3,
    last_name: "Johnson",
    first_name: "Michael",
    dob: "05/11/2014",
    language: "Spanish",
    special_need: "Dyslexia",
    parent_name: "Laura Johnson",
    relationship: "mother",
    phone: "647-345-6789",
    email: "laurajohnson@gmail.com",
    address: "6000 Bathurst St",
    credit: 100,
  },
  {
    id: 4,
    last_name: "Williams",
    first_name: "Emily",
    dob: "18/02/2016",
    language: "English",
    special_need: "None",
    parent_name: "David Williams",
    relationship: "father",
    phone: "647-456-7890",
    email: "davidwilliams@gmail.com",
    address: "7000 Eglinton Ave",
    credit: 200,
  },
  {
    id: 5,
    last_name: "Brown",
    first_name: "Daniel",
    dob: "12/12/2015",
    language: "German",
    special_need: "Autism",
    parent_name: "Sarah Brown",
    relationship: "mother",
    phone: "647-567-8901",
    email: "sarahbrown@gmail.com",
    address: "8000 Dundas St",
    credit: 250,
  },
  {
    id: 6,
    last_name: "Jones",
    first_name: "Jessica",
    dob: "25/03/2016",
    language: "Italian",
    special_need: "None",
    parent_name: "Matthew Jones",
    relationship: "father",
    phone: "647-678-9012",
    email: "matthewjones@gmail.com",
    address: "9000 Queen St",
    credit: 100,
  },
  {
    id: 7,
    last_name: "Garcia",
    first_name: "Maria",
    dob: "30/08/2015",
    language: "Portuguese",
    special_need: "ADHD",
    parent_name: "Carlos Garcia",
    relationship: "father",
    phone: "647-789-0123",
    email: "carlosgarcia@gmail.com",
    address: "1000 King St",
    credit: 300,
  },
  {
    id: 8,
    last_name: "Martinez",
    first_name: "Carlos",
    dob: "14/05/2016",
    language: "Spanish",
    special_need: "None",
    parent_name: "Ana Martinez",
    relationship: "mother",
    phone: "647-890-1234",
    email: "anamartinez@gmail.com",
    address: "1100 College St",
    credit: 200,
  },
  {
    id: 9,
    last_name: "Anderson",
    first_name: "Andrew",
    dob: "19/06/2015",
    language: "English",
    special_need: "Dyslexia",
    parent_name: "John Anderson",
    relationship: "father",
    phone: "647-901-2345",
    email: "johnanderson@gmail.com",
    address: "1200 Bloor St",
    credit: 150,
  },
  {
    id: 10,
    last_name: "Wilson",
    first_name: "David",
    dob: "10/09/2016",
    language: "French",
    special_need: "None",
    parent_name: "Laura Wilson",
    relationship: "mother",
    phone: "647-012-3456",
    email: "laurawilson@gmail.com",
    address: "1300 St. Clair Ave",
    credit: 200,
  },
  {
    id: 11,
    last_name: "Moore",
    first_name: "Sarah",
    dob: "22/04/2015",
    language: "Russian",
    special_need: "None",
    parent_name: "James Moore",
    relationship: "father",
    phone: "647-123-4567",
    email: "jamesmoore@gmail.com",
    address: "1400 Dundas St",
    credit: 150,
  },
  {
    id: 12,
    last_name: "Taylor",
    first_name: "Christopher",
    dob: "05/05/2016",
    language: "Japanese",
    special_need: "Autism",
    parent_name: "Alice Taylor",
    relationship: "mother",
    phone: "647-234-5678",
    email: "alicetaylor@gmail.com",
    address: "1500 Queen St",
    credit: 100,
  },
  {
    id: 13,
    last_name: "Lee",
    first_name: "Anna",
    dob: "18/06/2015",
    language: "Chinese",
    special_need: "None",
    parent_name: "Robert Lee",
    relationship: "father",
    phone: "647-345-6789",
    email: "robertlee@gmail.com",
    address: "1600 King St",
    credit: 250,
  },
  {
    id: 14,
    last_name: "White",
    first_name: "James",
    dob: "10/08/2016",
    language: "French",
    special_need: "None",
    parent_name: "Maria White",
    relationship: "mother",
    phone: "647-456-7890",
    email: "mariawhite@gmail.com",
    address: "1700 Bloor St",
    credit: 200,
  },
  {
    id: 15,
    last_name: "Harris",
    first_name: "Matthew",
    dob: "05/01/2015",
    language: "Spanish",
    special_need: "Dyslexia",
    parent_name: "Linda Harris",
    relationship: "mother",
    phone: "647-567-8901",
    email: "lindaharris@gmail.com",
    address: "1800 Yonge St",
    credit: 150,
  },
  {
    id: 16,
    last_name: "Clark",
    first_name: "Olivia",
    dob: "25/03/2016",
    language: "English",
    special_need: "None",
    parent_name: "David Clark",
    relationship: "father",
    phone: "647-678-9012",
    email: "davidclark@gmail.com",
    address: "1900 Queen St",
    credit: 100,
  },
  {
    id: 17,
    last_name: "Robinson",
    first_name: "Sophia",
    dob: "14/04/2015",
    language: "German",
    special_need: "ADHD",
    parent_name: "Emily Robinson",
    relationship: "mother",
    phone: "647-789-0123",
    email: "emilyrobinson@gmail.com",
    address: "2000 King St",
    credit: 300,
  },
  {
    id: 18,
    last_name: "Walker",
    first_name: "Liam",
    dob: "12/02/2016",
    language: "English",
    special_need: "None",
    parent_name: "William Walker",
    relationship: "father",
    phone: "647-890-1234",
    email: "williamwalker@gmail.com",
    address: "2100 Bloor St",
    credit: 200,
  },
  {
    id: 19,
    last_name: "Perez",
    first_name: "Lucas",
    dob: "27/06/2015",
    language: "Spanish",
    special_need: "Autism",
    parent_name: "Isabella Perez",
    relationship: "mother",
    phone: "647-901-2345",
    email: "isabellaperez@gmail.com",
    address: "2200 Yonge St",
    credit: 150,
  },
  {
    id: 20,
    last_name: "Hall",
    first_name: "Mia",
    dob: "15/08/2016",
    language: "French",
    special_need: "None",
    parent_name: "Michael Hall",
    relationship: "father",
    phone: "647-012-3456",
    email: "michaelhall@gmail.com",
    address: "2300 Queen St",
    credit: 200,
  },
  {
    id: 21,
    last_name: "Young",
    first_name: "Sophia",
    dob: "18/05/2015",
    language: "Chinese",
    special_need: "None",
    parent_name: "Emily Young",
    relationship: "mother",
    phone: "647-123-4567",
    email: "emilyyoung@gmail.com",
    address: "2400 King St",
    credit: 150,
  },
  {
    id: 22,
    last_name: "Allen",
    first_name: "Noah",
    dob: "05/07/2016",
    language: "German",
    special_need: "Dyslexia",
    parent_name: "Linda Allen",
    relationship: "mother",
    phone: "647-234-5678",
    email: "lindaallen@gmail.com",
    address: "2500 Bloor St",
    credit: 100,
  },
  {
    id: 23,
    last_name: "Hernandez",
    first_name: "Lucas",
    dob: "14/04/2015",
    language: "Spanish",
    special_need: "None",
    parent_name: "John Hernandez",
    relationship: "father",
    phone: "647-345-6789",
    email: "johnhernandez@gmail.com",
    address: "2600 Yonge St",
    credit: 250,
  },
  {
    id: 24,
    last_name: "King",
    first_name: "Emma",
    dob: "10/11/2016",
    language: "French",
    special_need: "None",
    parent_name: "James King",
    relationship: "father",
    phone: "647-456-7890",
    email: "jamesking@gmail.com",
    address: "2700 Queen St",
    credit: 200,
  },
  {
    id: 25,
    last_name: "Wright",
    first_name: "Ava",
    dob: "22/02/2015",
    language: "English",
    special_need: "None",
    parent_name: "Michael Wright",
    relationship: "father",
    phone: "647-567-8901",
    email: "michaelwright@gmail.com",
    address: "2800 King St",
    credit: 150,
  },
  {
    id: 26,
    last_name: "Lopez",
    first_name: "Liam",
    dob: "18/08/2016",
    language: "Spanish",
    special_need: "ADHD",
    parent_name: "Linda Lopez",
    relationship: "mother",
    phone: "647-678-9012",
    email: "lindalopez@gmail.com",
    address: "2900 Bloor St",
    credit: 100,
  },
  {
    id: 27,
    last_name: "Scott",
    first_name: "Isabella",
    dob: "27/04/2015",
    language: "Italian",
    special_need: "None",
    parent_name: "David Scott",
    relationship: "father",
    phone: "647-789-0123",
    email: "davidscott@gmail.com",
    address: "3000 Yonge St",
    credit: 300,
  },
  {
    id: 28,
    last_name: "Green",
    first_name: "Ethan",
    dob: "05/05/2016",
    language: "French",
    special_need: "None",
    parent_name: "Laura Green",
    relationship: "mother",
    phone: "647-890-1234",
    email: "lauragreen@gmail.com",
    address: "3100 Queen St",
    credit: 200,
  },
  {
    id: 29,
    last_name: "Baker",
    first_name: "Lucas",
    dob: "18/09/2015",
    language: "English",
    special_need: "None",
    parent_name: "James Baker",
    relationship: "father",
    phone: "647-901-2345",
    email: "jamesbaker@gmail.com",
    address: "3200 King St",
    credit: 150,
  },
  {
    id: 30,
    last_name: "Adams",
    first_name: "Ella",
    dob: "22/10/2016",
    language: "Spanish",
    special_need: "Dyslexia",
    parent_name: "Emily Adams",
    relationship: "mother",
    phone: "647-012-3456",
    email: "emilyadams@gmail.com",
    address: "3300 Bloor St",
    credit: 100,
  },
  {
    id: 31,
    last_name: "Nelson",
    first_name: "Mia",
    dob: "27/03/2015",
    language: "German",
    special_need: "None",
    parent_name: "Michael Nelson",
    relationship: "father",
    phone: "647-123-4567",
    email: "michaelnelson@gmail.com",
    address: "3400 Yonge St",
    credit: 250,
  },
  {
    id: 32,
    last_name: "Carter",
    first_name: "Ava",
    dob: "18/07/2016",
    language: "English",
    special_need: "None",
    parent_name: "Linda Carter",
    relationship: "mother",
    phone: "647-234-5678",
    email: "lindacarter@gmail.com",
    address: "3500 Queen St",
    credit: 200,
  },
  {
    id: 33,
    last_name: "Mitchell",
    first_name: "Sophia",
    dob: "12/11/2015",
    language: "Spanish",
    special_need: "ADHD",
    parent_name: "James Mitchell",
    relationship: "father",
    phone: "647-345-6789",
    email: "jamesmitchell@gmail.com",
    address: "3600 King St",
    credit: 150,
  },
  {
    id: 34,
    last_name: "Perez",
    first_name: "Lucas",
    dob: "05/08/2016",
    language: "French",
    special_need: "None",
    parent_name: "Emily Perez",
    relationship: "mother",
    phone: "647-456-7890",
    email: "emilyperez@gmail.com",
    address: "3700 Bloor St",
    credit: 100,
  },
  {
    id: 35,
    last_name: "Roberts",
    first_name: "Oliver",
    dob: "14/04/2015",
    language: "German",
    special_need: "Autism",
    parent_name: "David Roberts",
    relationship: "father",
    phone: "647-567-8901",
    email: "davidroberts@gmail.com",
    address: "3800 Yonge St",
    credit: 150,
  },
  {
    id: 36,
    last_name: "Turner",
    first_name: "Lucas",
    dob: "12/10/2016",
    language: "English",
    special_need: "None",
    parent_name: "Laura Turner",
    relationship: "mother",
    phone: "647-678-9012",
    email: "lauraturner@gmail.com",
    address: "3900 Queen St",
    credit: 200,
  },
  {
    id: 37,
    last_name: "Phillips",
    first_name: "Ava",
    dob: "27/07/2015",
    language: "Spanish",
    special_need: "None",
    parent_name: "Michael Phillips",
    relationship: "father",
    phone: "647-789-0123",
    email: "michaelphillips@gmail.com",
    address: "4000 King St",
    credit: 250,
  },
  {
    id: 38,
    last_name: "Campbell",
    first_name: "Mia",
    dob: "10/09/2016",
    language: "French",
    special_need: "ADHD",
    parent_name: "Emily Campbell",
    relationship: "mother",
    phone: "647-890-1234",
    email: "emilycampbell@gmail.com",
    address: "4100 Bloor St",
    credit: 200,
  },
  {
    id: 39,
    last_name: "Parker",
    first_name: "Liam",
    dob: "22/05/2015",
    language: "German",
    special_need: "None",
    parent_name: "David Parker",
    relationship: "father",
    phone: "647-901-2345",
    email: "davidparker@gmail.com",
    address: "4200 Yonge St",
    credit: 150,
  },
  {
    id: 40,
    last_name: "Evans",
    first_name: "Isabella",
    dob: "12/01/2016",
    language: "English",
    special_need: "Dyslexia",
    parent_name: "James Evans",
    relationship: "father",
    phone: "647-012-3456",
    email: "jamesevans@gmail.com",
    address: "4300 Queen St",
    credit: 100,
  },
  {
    id: 41,
    last_name: "Edwards",
    first_name: "Lucas",
    dob: "18/03/2015",
    language: "French",
    special_need: "None",
    parent_name: "Emily Edwards",
    relationship: "mother",
    phone: "647-123-4567",
    email: "emilyedwards@gmail.com",
    address: "4400 King St",
    credit: 150,
  },
  {
    id: 42,
    last_name: "Collins",
    first_name: "Liam",
    dob: "14/11/2016",
    language: "Spanish",
    special_need: "None",
    parent_name: "Michael Collins",
    relationship: "father",
    phone: "647-234-5678",
    email: "michaelcollins@gmail.com",
    address: "4500 Bloor St",
    credit: 250,
  },
  {
    id: 43,
    last_name: "Stewart",
    first_name: "Sophia",
    dob: "05/06/2015",
    language: "German",
    special_need: "None",
    parent_name: "Linda Stewart",
    relationship: "mother",
    phone: "647-345-6789",
    email: "lindastewart@gmail.com",
    address: "4600 Yonge St",
    credit: 200,
  },
  {
    id: 44,
    last_name: "Sanchez",
    first_name: "Lucas",
    dob: "18/02/2016",
    language: "English",
    special_need: "ADHD",
    parent_name: "James Sanchez",
    relationship: "father",
    phone: "647-456-7890",
    email: "jamessanchez@gmail.com",
    address: "4700 Queen St",
    credit: 150,
  },
  {
    id: 45,
    last_name: "Morris",
    first_name: "Ava",
    dob: "10/12/2015",
    language: "French",
    special_need: "None",
    parent_name: "Emily Morris",
    relationship: "mother",
    phone: "647-567-8901",
    email: "emilymorris@gmail.com",
    address: "4800 King St",
    credit: 100,
  },
  {
    id: 46,
    last_name: "Rogers",
    first_name: "Ethan",
    dob: "22/04/2016",
    language: "German",
    special_need: "None",
    parent_name: "Michael Rogers",
    relationship: "father",
    phone: "647-678-9012",
    email: "michaelrogers@gmail.com",
    address: "4900 Bloor St",
    credit: 150,
  },
  {
    id: 47,
    last_name: "Reed",
    first_name: "Isabella",
    dob: "18/08/2015",
    language: "English",
    special_need: "None",
    parent_name: "David Reed",
    relationship: "father",
    phone: "647-789-0123",
    email: "davidreed@gmail.com",
    address: "5000 Yonge St",
    credit: 200,
  },
  {
    id: 48,
    last_name: "Cook",
    first_name: "Lucas",
    dob: "10/01/2016",
    language: "Spanish",
    special_need: "Autism",
    parent_name: "Emily Cook",
    relationship: "mother",
    phone: "647-890-1234",
    email: "emilycook@gmail.com",
    address: "5100 Queen St",
    credit: 150,
  },
  {
    id: 49,
    last_name: "Morgan",
    first_name: "Liam",
    dob: "14/05/2016",
    language: "French",
    special_need: "None",
    parent_name: "James Morgan",
    relationship: "father",
    phone: "647-901-2345",
    email: "jamesmorgan@gmail.com",
    address: "5200 King St",
    credit: 100,
  },
  {
    id: 50,
    last_name: "Bell",
    first_name: "Mia",
    dob: "22/06/2015",
    language: "English",
    special_need: "None",
    parent_name: "Laura Bell",
    relationship: "mother",
    phone: "647-012-3456",
    email: "laurabell@gmail.com",
    address: "5300 Bloor St",
    credit: 150,
  },
];

export { columns, participants };
