// no longer needed

import React from "react";

const columns = [
  { name: "ID", uid: "id", sortable: true },
  { name: "FIRST NAME", uid: "first_name", sortable: true },
  { name: "LAST NAME", uid: "last_name", sortable: true },
  { name: "DATE OF BIRTH", uid: "dob" },
  { name: "LANGUAGE", uid: "language", sortable: true },
  { name: "SPECIAL NEEDS", uid: "special_need", sortable: true },
  { name: "GUARDIAN 1 NAME", uid: "parent_name1", sortable: true },
  { name: "RELATIONSHIP 1", uid: "relationship1", sortable: true },
  { name: "GUARDIAN 2 NAME", uid: "parent_name2", sortable: true },
  { name: "RELATIONSHIP 2", uid: "relationship2", sortable: true },
  { name: "PHONE", uid: "phone", sortable: true },
  { name: "EMAIL", uid: "email" },
  { name: "ADDRESS", uid: "address" },
  { name: "CREDIT", uid: "credit", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const participants = [
  {
    id: 1,
    first_name: "John",
    last_name: "Doe",
    dob: "13/05/2016",
    language: "English",
    special_need: "ADHD",
    parent_name1: "Jason Doe",
    relationship1: "father",
    parent_name2: "Jenny Doe",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 200,
  },
  {
    id: 2,
    first_name: "Emma",
    last_name: "Smith",
    dob: "22/11/2015",
    language: "French",
    special_need: "None",
    parent_name1: "Robert Smith",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 3,
    first_name: "Liam",
    last_name: "Johnson",
    dob: "18/04/2016",
    language: "Spanish",
    special_need: "None",
    parent_name1: "Michael Johnson",
    relationship1: "father",
    parent_name2: "Sarah Johnson",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 100,
  },
  {
    id: 4,
    first_name: "Sophia",
    last_name: "Williams",
    dob: "07/02/2015",
    language: "German",
    special_need: "Dyslexia",
    parent_name1: "David Williams",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 5,
    first_name: "Lucas",
    last_name: "Brown",
    dob: "13/05/2016",
    language: "Chinese",
    special_need: "Autism",
    parent_name1: "James Brown",
    relationship1: "father",
    parent_name2: "Emily Brown",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 200,
  },
  {
    id: 6,
    first_name: "Isabella",
    last_name: "Jones",
    dob: "22/11/2015",
    language: "English",
    special_need: "None",
    parent_name1: "Richard Jones",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 7,
    first_name: "Noah",
    last_name: "Garcia",
    dob: "18/04/2016",
    language: "French",
    special_need: "None",
    parent_name1: "Steven Garcia",
    relationship1: "father",
    parent_name2: "Linda Garcia",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 100,
  },
  {
    id: 8,
    first_name: "Mia",
    last_name: "Martinez",
    dob: "07/02/2015",
    language: "Spanish",
    special_need: "ADHD",
    parent_name1: "Thomas Martinez",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 9,
    first_name: "Ethan",
    last_name: "Miller",
    dob: "13/05/2016",
    language: "German",
    special_need: "None",
    parent_name1: "William Miller",
    relationship1: "father",
    parent_name2: "Jessica Miller",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 200,
  },
  {
    id: 10,
    first_name: "Ava",
    last_name: "Davis",
    dob: "22/11/2015",
    language: "Chinese",
    special_need: "None",
    parent_name1: "Edward Davis",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 11,
    first_name: "Alexander",
    last_name: "Rodriguez",
    dob: "18/04/2016",
    language: "English",
    special_need: "Autism",
    parent_name1: "Brian Rodriguez",
    relationship1: "father",
    parent_name2: "Jennifer Rodriguez",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 100,
  },
  {
    id: 12,
    first_name: "Olivia",
    last_name: "Martinez",
    dob: "07/02/2015",
    language: "French",
    special_need: "None",
    parent_name1: "Charles Martinez",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 13,
    first_name: "Elijah",
    last_name: "Hernandez",
    dob: "13/05/2016",
    language: "Spanish",
    special_need: "Dyslexia",
    parent_name1: "Christopher Hernandez",
    relationship1: "father",
    parent_name2: "Laura Hernandez",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 200,
  },
  {
    id: 14,
    first_name: "Charlotte",
    last_name: "Lopez",
    dob: "22/11/2015",
    language: "German",
    special_need: "None",
    parent_name1: "Daniel Lopez",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 15,
    first_name: "Benjamin",
    last_name: "Gonzalez",
    dob: "18/04/2016",
    language: "Chinese",
    special_need: "ADHD",
    parent_name1: "Joshua Gonzalez",
    relationship1: "father",
    parent_name2: "Stephanie Gonzalez",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 100,
  },
  {
    id: 16,
    first_name: "Amelia",
    last_name: "Wilson",
    dob: "07/02/2015",
    language: "English",
    special_need: "None",
    parent_name1: "Anthony Wilson",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 17,
    first_name: "Jacob",
    last_name: "Anderson",
    dob: "13/05/2016",
    language: "French",
    special_need: "None",
    parent_name1: "Kevin Anderson",
    relationship1: "father",
    parent_name2: "Rebecca Anderson",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 200,
  },
  {
    id: 18,
    first_name: "Evelyn",
    last_name: "Thomas",
    dob: "22/11/2015",
    language: "Spanish",
    special_need: "None",
    parent_name1: "Andrew Thomas",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 19,
    first_name: "James",
    last_name: "Taylor",
    dob: "18/04/2016",
    language: "German",
    special_need: "Dyslexia",
    parent_name1: "Joseph Taylor",
    relationship1: "father",
    parent_name2: "Michelle Taylor",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 100,
  },
  {
    id: 20,
    first_name: "Harper",
    last_name: "Moore",
    dob: "07/02/2015",
    language: "Chinese",
    special_need: "None",
    parent_name1: "Matthew Moore",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 21,
    first_name: "Henry",
    last_name: "Jackson",
    dob: "13/05/2016",
    language: "English",
    special_need: "None",
    parent_name1: "Ryan Jackson",
    relationship1: "father",
    parent_name2: "Megan Jackson",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 200,
  },
  {
    id: 22,
    first_name: "Avery",
    last_name: "Martin",
    dob: "22/11/2015",
    language: "French",
    special_need: "None",
    parent_name1: "Kyle Martin",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 23,
    first_name: "Sebastian",
    last_name: "Lee",
    dob: "18/04/2016",
    language: "Spanish",
    special_need: "Autism",
    parent_name1: "Zachary Lee",
    relationship1: "father",
    parent_name2: "Amanda Lee",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 100,
  },
  {
    id: 24,
    first_name: "Aria",
    last_name: "Perez",
    dob: "07/02/2015",
    language: "German",
    special_need: "None",
    parent_name1: "Jeffrey Perez",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 25,
    first_name: "Michael",
    last_name: "White",
    dob: "13/05/2016",
    language: "Chinese",
    special_need: "ADHD",
    parent_name1: "Tyler White",
    relationship1: "father",
    parent_name2: "Victoria White",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 200,
  },
  {
    id: 26,
    first_name: "Scarlett",
    last_name: "Harris",
    dob: "22/11/2015",
    language: "English",
    special_need: "None",
    parent_name1: "Ethan Harris",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 27,
    first_name: "Daniel",
    last_name: "Clark",
    dob: "18/04/2016",
    language: "French",
    special_need: "None",
    parent_name1: "Gabriel Clark",
    relationship1: "father",
    parent_name2: "Hannah Clark",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 100,
  },
  {
    id: 28,
    first_name: "Grace",
    last_name: "Lewis",
    dob: "07/02/2015",
    language: "Spanish",
    special_need: "Dyslexia",
    parent_name1: "Logan Lewis",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 29,
    first_name: "Matthew",
    last_name: "Robinson",
    dob: "13/05/2016",
    language: "German",
    special_need: "None",
    parent_name1: "Brandon Robinson",
    relationship1: "father",
    parent_name2: "Grace Robinson",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 200,
  },
  {
    id: 30,
    first_name: "Lily",
    last_name: "Walker",
    dob: "22/11/2015",
    language: "Chinese",
    special_need: "None",
    parent_name1: "Nicholas Walker",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 31,
    first_name: "David",
    last_name: "Young",
    dob: "18/04/2016",
    language: "English",
    special_need: "Autism",
    parent_name1: "Jordan Young",
    relationship1: "father",
    parent_name2: "Anna Young",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 100,
  },
  {
    id: 32,
    first_name: "Victoria",
    last_name: "King",
    dob: "07/02/2015",
    language: "French",
    special_need: "None",
    parent_name1: "Sean King",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 33,
    first_name: "Joseph",
    last_name: "Wright",
    dob: "13/05/2016",
    language: "Spanish",
    special_need: "ADHD",
    parent_name1: "Christian Wright",
    relationship1: "father",
    parent_name2: "Rachel Wright",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 200,
  },
  {
    id: 34,
    first_name: "Layla",
    last_name: "Scott",
    dob: "22/11/2015",
    language: "German",
    special_need: "None",
    parent_name1: "Blake Scott",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 35,
    first_name: "Samuel",
    last_name: "Green",
    dob: "18/04/2016",
    language: "Chinese",
    special_need: "None",
    parent_name1: "Connor Green",
    relationship1: "father",
    parent_name2: "Isabella Green",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 100,
  },
  {
    id: 36,
    first_name: "Zoey",
    last_name: "Adams",
    dob: "07/02/2015",
    language: "English",
    special_need: "Dyslexia",
    parent_name1: "Adrian Adams",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 37,
    first_name: "Joshua",
    last_name: "Baker",
    dob: "13/05/2016",
    language: "French",
    special_need: "None",
    parent_name1: "Gavin Baker",
    relationship1: "father",
    parent_name2: "Lucy Baker",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 200,
  },
  {
    id: 38,
    first_name: "Hannah",
    last_name: "Hill",
    dob: "22/11/2015",
    language: "Spanish",
    special_need: "None",
    parent_name1: "Owen Hill",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 39,
    first_name: "William",
    last_name: "Nelson",
    dob: "18/04/2016",
    language: "German",
    special_need: "None",
    parent_name1: "Aaron Nelson",
    relationship1: "father",
    parent_name2: "Natalie Nelson",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 100,
  },
  {
    id: 40,
    first_name: "Sofia",
    last_name: "Carter",
    dob: "07/02/2015",
    language: "Chinese",
    special_need: "Autism",
    parent_name1: "Nathan Carter",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 41,
    first_name: "James",
    last_name: "Mitchell",
    dob: "13/05/2016",
    language: "English",
    special_need: "None",
    parent_name1: "Cameron Mitchell",
    relationship1: "father",
    parent_name2: "Ella Mitchell",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 200,
  },
  {
    id: 42,
    first_name: "Grace",
    last_name: "Perez",
    dob: "22/11/2015",
    language: "French",
    special_need: "None",
    parent_name1: "Austin Perez",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 43,
    first_name: "Dylan",
    last_name: "Roberts",
    dob: "18/04/2016",
    language: "Spanish",
    special_need: "Dyslexia",
    parent_name1: "Hunter Roberts",
    relationship1: "father",
    parent_name2: "Madison Roberts",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 100,
  },
  {
    id: 44,
    first_name: "Eleanor",
    last_name: "Turner",
    dob: "07/02/2015",
    language: "German",
    special_need: "None",
    parent_name1: "Carson Turner",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 45,
    first_name: "Oliver",
    last_name: "Phillips",
    dob: "13/05/2016",
    language: "Chinese",
    special_need: "None",
    parent_name1: "Colton Phillips",
    relationship1: "father",
    parent_name2: "Avery Phillips",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 200,
  },
  {
    id: 46,
    first_name: "Zoey",
    last_name: "Campbell",
    dob: "22/11/2015",
    language: "English",
    special_need: "None",
    parent_name1: "Miles Campbell",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 47,
    first_name: "Carter",
    last_name: "Parker",
    dob: "18/04/2016",
    language: "French",
    special_need: "None",
    parent_name1: "Brody Parker",
    relationship1: "father",
    parent_name2: "Savannah Parker",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 100,
  },
  {
    id: 48,
    first_name: "Penelope",
    last_name: "Evans",
    dob: "07/02/2015",
    language: "Spanish",
    special_need: "Autism",
    parent_name1: "Jason Evans",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
  {
    id: 49,
    first_name: "Nathan",
    last_name: "Edwards",
    dob: "13/05/2016",
    language: "German",
    special_need: "None",
    parent_name1: "Joel Edwards",
    relationship1: "father",
    parent_name2: "Mia Edwards",
    relationship2: "mother",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 200,
  },
  {
    id: 50,
    first_name: "Victoria",
    last_name: "Collins",
    dob: "22/11/2015",
    language: "Chinese",
    special_need: "None",
    parent_name1: "Ryder Collins",
    relationship1: "father",
    phone: "647-123-4567",
    email: "cics@gmail.com",
    address: "4002 Sheppard Ave",
    credit: 150,
  },
];

export { columns, participants };
