import React from "react";

const PaymentStatusOptions = [
  { name: "Paid", uid: "paid" },
  { name: "Unpaid", uid: "unpaid" },
];

const courses = [
  {
    id: 1,
    course_name: "1 Kinder Enrichment Camp",
    class_name: "1 Kids Can Cook",
    status: "active",
    enrolled_time: "June 15, 2024",
    course_date: "July 2 to 5 (Tue-Fri) 9am-3pm",
    beforeOrAfterCamp: "After Camp",
    pick_up_arrangement: "Pickup by parent",
    isDiscountCodeApplied: true,
    isCreditApplied: false,
    feeAmount: 250,
    payment_status: "paid",
  },
  {
    id: 2,
    course_name: "2 Kinder Enrichment Camp",
    class_name: "2 Kids Can Cook",
    status: "active",
    enrolled_time: "June 15, 2024",
    course_date: "July 2 to 5 (Tue-Fri) 9am-3pm",
    beforeOrAfterCamp: "After Camp",
    pick_up_arrangement: "Pickup by parent",
    isDiscountCodeApplied: true,
    isCreditApplied: false,
    feeAmount: 250,
    payment_status: "paid",
  },
  {
    id: 3,
    course_name: "3 Kinder Enrichment Camp",
    class_name: "3 Kids Can Cook",
    status: "active",
    enrolled_time: "June 15, 2024",
    course_date: "July 2 to 5 (Tue-Fri) 9am-3pm",
    beforeOrAfterCamp: "After Camp",
    pick_up_arrangement: "Pickup by parent",
    isDiscountCodeApplied: true,
    isCreditApplied: false,
    feeAmount: 250,
    payment_status: "paid",
  },
  {
    id: 4,
    course_name: "Kinder Enrichment Camp",
    class_name: "4 Kids Can Cook",
    status: "active",
    enrolled_time: "June 15, 2024",
    course_date: "July 2 to 5 (Tue-Fri) 9am-3pm",
    beforeOrAfterCamp: "After Camp",
    pick_up_arrangement: "Pickup by parent",
    isDiscountCodeApplied: true,
    isCreditApplied: false,
    feeAmount: 250,
    payment_status: "paid",
  },
  {
    id: 5,
    course_name: "Kinder Enrichment Camp",
    class_name: "5 Kids Can Cook",
    status: "active",
    enrolled_time: "June 15, 2024",
    course_date: "July 2 to 5 (Tue-Fri) 9am-3pm",
    beforeOrAfterCamp: "After Camp",
    pick_up_arrangement: "Pickup by parent",
    isDiscountCodeApplied: true,
    isCreditApplied: false,
    feeAmount: 250,
    payment_status: "paid",
  },
  {
    id: 6,
    course_name: "Kinder Enrichment Camp",
    class_name: "Kids Can Cook",
    status: "active",
    enrolled_time: "June 15, 2024",
    course_date: "July 2 to 5 (Tue-Fri) 9am-3pm",
    beforeOrAfterCamp: "After Camp",
    pick_up_arrangement: "Pickup by parent",
    isDiscountCodeApplied: true,
    isCreditApplied: false,
    feeAmount: 250,
    payment_status: "paid",
  },
  {
    id: 7,
    course_name: "Kinder Enrichment Camp",
    class_name: "Kids Can Cook",
    status: "active",
    enrolled_time: "June 15, 2024",
    course_date: "July 2 to 5 (Tue-Fri) 9am-3pm",
    beforeOrAfterCamp: "After Camp",
    pick_up_arrangement: "Pickup by parent",
    isDiscountCodeApplied: true,
    isCreditApplied: false,
    feeAmount: 250,
    payment_status: "paid",
  },
  {
    id: 8,
    course_name: "Kinder Enrichment Camp",
    class_name: "Kids Can Cook",
    status: "active",
    enrolled_time: "June 15, 2024",
    course_date: "July 2 to 5 (Tue-Fri) 9am-3pm",
    beforeOrAfterCamp: "After Camp",
    pick_up_arrangement: "Pickup by parent",
    isDiscountCodeApplied: true,
    isCreditApplied: false,
    feeAmount: 250,
    payment_status: "paid",
  },
];

export { courses };
